feat: support for doctype retrieval
kornelski/xml-rs pull request #26
Opened 2024-08-20 01:44 UTC by EstebanBorai

Provides support for `DOCTYPE` retrieval in `PullParser`.

2024-08-25 19:00 UTC, kornelski commented on src/reader/parser.rs
> +        &self.data.doctype
`&Option` should never be used. `Option<&` is equivalent, and more useful in general.

```suggestion
        self.data.doctype.as_deref()
```

2024-08-25 19:01 UTC, kornelski commented on src/reader/parser/inside_doctype.rs
> +            doctype.push_str(t.to_string().as_str());
Avoids allocation `use fmt::Write`:

```suggestion
            write!(&mut doctype, "{t}").ok()?;
```

2024-08-25 20:28 UTC, EstebanBorai commented
@kornelski thanks so much for the suggestions!

2024-08-27 17:03 UTC, kornelski commented
The tests are failing

2024-08-27 17:05 UTC, kornelski requested changes
Please test your work

2024-08-27 17:05 UTC, kornelski requested changes
Please test your work

2024-08-28 02:51 UTC, EstebanBorai commented
> Please test your work 

Of course!

2024-09-02 02:50 UTC, merged

2024-09-02 21:50 UTC, EstebanBorai commented
Hi @kornelski I think this pr was merged accidentally?